---
title: "proficiency-test-II"
author: "Cameron Flores"
format: pdf
editor: visual
---

## Task-1

```{r}
for(i in 1:3){
print(mtcars$mpg[i])
}
```


## Task-2
```{r}
count_above <- function(x, c){ # creates count_above as a function, sets x as the vector and c as the cutoff
  count <- 0 # sets the count to 0
  
for(i in 1:length(x)){ # for i is from 1 to the length of x
  if((1:length(x[i])) > c){ # if an index is greater than the cutoff
    count <- count + 1 #adds +1 to the counter
  }
}
  return(count) #returns count
}
```

```{r}
count_aboveandequal <- function(x, c){ # creates count_above as a function, sets x as the vector and c as the cutoff
  count <- 0 # sets the count to 0
  
for(i in 1:length(x)){ # for i is from 1 to the length of x
  if(i >= c){ # if i is greater than or equal to c
    count <- count + 1 #adds +1 to the counter
  }
}
  return(count) #returns count
}
```

```{r}
count_above(iris$Sepal.Length,6)
```

```{r}
count_aboveandequal(mtcars$disp, 150)
```

## Task 3
Masking functions is when you cover up a loaded in function that was installed, these laoded in functions usually override basic R studio functions.

## Task 4
```{r}
iris$Sepal.Length[1]

iris[1,1]
```
it returns the first value in the Sepal.Length column of iris



